source 'http://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib', require: false
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem "tux"
gem 'sinatra-flash'
gem 'bootstrap'
gem 'dead_end'
gem 'kimurai'
gem 'mechanize'
gem 'dotenv'
# gem 'coffee-script'
# gem 'sinatra-respond_to'
# gem 'sinatra-partial'